// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTUkKGUUwIDN22vYPjXsbGn2deivqa8Q',
    appId: '1:37129895463:web:e7bbc8a87dd8915f485802',
    messagingSenderId: '37129895463',
    projectId: 'flutter-whatsapp-clone-cbb54',
    authDomain: 'flutter-whatsapp-clone-cbb54.firebaseapp.com',
    storageBucket: 'flutter-whatsapp-clone-cbb54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xquKCRxoFohdI3MnoIYRAOqH_Q1IsSo',
    appId: '1:37129895463:android:530fe6d299b858a9485802',
    messagingSenderId: '37129895463',
    projectId: 'flutter-whatsapp-clone-cbb54',
    storageBucket: 'flutter-whatsapp-clone-cbb54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcp2IJGlgwXTsJbzBvEbiCvuzjgZo2dTI',
    appId: '1:37129895463:ios:3efb4ff5fc9cac9d485802',
    messagingSenderId: '37129895463',
    projectId: 'flutter-whatsapp-clone-cbb54',
    storageBucket: 'flutter-whatsapp-clone-cbb54.appspot.com',
    iosClientId: '37129895463-cr39k8ficvjufe4202e7amhv7sjokcao.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcp2IJGlgwXTsJbzBvEbiCvuzjgZo2dTI',
    appId: '1:37129895463:ios:3efb4ff5fc9cac9d485802',
    messagingSenderId: '37129895463',
    projectId: 'flutter-whatsapp-clone-cbb54',
    storageBucket: 'flutter-whatsapp-clone-cbb54.appspot.com',
    iosClientId: '37129895463-cr39k8ficvjufe4202e7amhv7sjokcao.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
